### PR TITLE
version bump

### PR DESCRIPTION
**Pull request by JevgenijusB**
@henrikbjorn 

please release asap:)

### CODE REVIEW

**Comment by henrikbjorn** [comment]
We can't release a version with 6.0 support when travis is failing.

If you can fix it. Then please do! I don't have much time currently to look into it.

When the 6.0 tests are fixed then I will cut a new release. Thanks.

**Comment by JevgenijusB** [comment]
Have You pushed to rubygems.org? :)

**Comment by henrikbjorn** [comment]
Done.

**Comment by henrikbjorn** [comment]
Thank you very much for your work on this. Every developer here appreciates it 😊 @JevgenijusB

**Pull request merged**
