### PR TITLE
Added rails 6 support

### PR DESCRIPTION
**Pull request by JevgenijusB**
@mkyed @kaspth

### CODE REVIEW

**Comment by martynasdub** [comment]
Can we get this merged?

**Comment by henrikbjorn** [comment]
The tests on travis are failing. I think it is because we are trying to do `gem install bundler` which travis does on our behalf. Possible to tweak the PR to remove the `gem install bundler` line ? 😊

**Comment by JevgenijusB** [comment]
Looks like build is passing now:)

**Comment by henrikbjorn** [comment]
@JevgenijusB Yeah, It needed a bit more. Please rebase with master 😊

**Pull request merged**
